### ISSUE TITLE
Создать вкладку "Проект"

### ISSUE THREAD

**Issue by willam2007** [willam2007/wps#5]
Создать вкладку в верхнем блоке - Проект (/Создать проект).
В данный момент времени проект несет в себе только одно полотно(альбом, лист). Пусть лист будет белым(заранее понять как в будущем можно нести за ним другой цвет).
Находясь во вкладке, пользователь должен иметь возможность создать проект разного размера. Для начало можно сделать пару фиксированных, и по возможности сделать кастомный.(N x N). 
 @CuteBanMachine 13.10.2024

**Comment by CuteBanMachine** [comment]
я сижу в метре от тебя. ты бы еще в тимсе писал

**Comment by CuteBanMachine** [comment]
done :)
